[package]
name = "RUST-Projects"
version = "0.1.0"
authors = ["Rajdeep Bandopadhyay <rajdeepbandopadhyay@gmail.com>"]
edition = "2018"

[dependencies]
rust-crypto = "^0.2"
blake2 = "0.6"
digest = { version = "0.6", features = ["std"]}